// Demo/örnek veriler — Veritabanı bağlanmadan önce UI'ı test etmek için
import type { ContentCard } from "@/types/content";

export const demoHeroItems: ContentCard[] = [
  {
    id: "1",
    title: "The Last of Us",
    originalTitle: "The Last of Us",
    slug: "the-last-of-us",
    type: "SERIES",
    description:
      "Ölümcül bir enfeksiyon modern uygarlığı yok etmiştir. Hayatta kalan Joel, 14 yaşındaki Ellie'yi kaçak olarak baskıcı bir karantina bölgesinin dışına çıkarmakla görevlendirilir. Basit gibi görünen bu iş, ikisinin hayatını sonsuza dek değiştirecek acımasız bir yolculuğa dönüşür.",
    posterUrl: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    tmdbId: 100088,
    imdbRating: 8.8,
    releaseYear: 2023,
    durationMinutes: 55,
    country: "ABD",
    language: "İngilizce",
    quality: "4K",
    viewCount: 125400,
    status: "ACTIVE",
    genres: [
      { id: 1, name: "Drama", slug: "drama" },
      { id: 2, name: "Aksiyon", slug: "aksiyon" },
      { id: 3, name: "Macera", slug: "macera" },
    ],
  },
  {
    id: "2",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    slug: "oppenheimer",
    type: "MOVIE",
    description:
      "Amerikalı bilim insanı J. Robert Oppenheimer'ın hikâyesi ve atom bombasının geliştirilmesindeki rolü. İkinci Dünya Savaşı sırasında Manhattan Projesi'ne liderlik eden Oppenheimer, insanlık tarihinin en yıkıcı silahını yaratmanın ağır yükünü taşır.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    tmdbId: 872585,
    imdbRating: 8.5,
    releaseYear: 2023,
    durationMinutes: 180,
    country: "ABD",
    language: "İngilizce",
    quality: "4K",
    viewCount: 98200,
    status: "ACTIVE",
    genres: [
      { id: 1, name: "Drama", slug: "drama" },
      { id: 4, name: "Tarih", slug: "tarih" },
      { id: 5, name: "Gerilim", slug: "gerilim" },
    ],
  },
  {
    id: "3",
    title: "House of the Dragon",
    originalTitle: "House of the Dragon",
    slug: "house-of-the-dragon",
    type: "SERIES",
    description:
      "Game of Thrones evreninde geçen bu dizi, Targaryen hanedanının iç savaşını konu alır. Demir Taht'ın varisi kim olacak? Ejderhalar geri döndü ve Westeros'un kaderi bir kez daha ateş ve kanla şekillenecek.",
    posterUrl: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    tmdbId: 94997,
    imdbRating: 8.4,
    releaseYear: 2022,
    durationMinutes: 60,
    country: "ABD",
    language: "İngilizce",
    quality: "HD",
    viewCount: 87300,
    status: "ACTIVE",
    genres: [
      { id: 1, name: "Drama", slug: "drama" },
      { id: 6, name: "Fantastik", slug: "fantastik" },
      { id: 2, name: "Aksiyon", slug: "aksiyon" },
    ],
  },
  {
    id: "4",
    title: "Dune: Part Two",
    originalTitle: "Dune: Part Two",
    slug: "dune-part-two",
    type: "MOVIE",
    description:
      "Paul Atreides, galaksinin geleceğini değiştirecek bir savaşı önlemek için Chani ve Fremen'lerle birlikte hareket eder. İntikam ve kader arasında kalan Paul, evreni tehdit eden güçlere karşı en büyük sınavıyla yüzleşir.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    tmdbId: 693134,
    imdbRating: 8.6,
    releaseYear: 2024,
    durationMinutes: 166,
    country: "ABD",
    language: "İngilizce",
    quality: "4K",
    viewCount: 76500,
    status: "ACTIVE",
    genres: [
      { id: 7, name: "Bilim Kurgu", slug: "bilim-kurgu" },
      { id: 3, name: "Macera", slug: "macera" },
      { id: 1, name: "Drama", slug: "drama" },
    ],
  },
  {
    id: "5",
    title: "Wednesday",
    originalTitle: "Wednesday",
    slug: "wednesday",
    type: "SERIES",
    description:
      "Addams Ailesi'nin kızı Wednesday, Nevermore Akademisi'ndeki öğrenci yaşamıyla başa çıkmaya çalışırken, kasabayı dehşete düşüren gizemli cinayet serisini çözmeye çalışır.",
    posterUrl: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/iHSwvRVsNBEPqFA2TRcaZoGpAQZ.jpg",
    tmdbId: 119051,
    imdbRating: 8.1,
    releaseYear: 2022,
    durationMinutes: 45,
    country: "ABD",
    language: "İngilizce",
    quality: "HD",
    viewCount: 142000,
    status: "ACTIVE",
    genres: [
      { id: 8, name: "Komedi", slug: "komedi" },
      { id: 9, name: "Gizem", slug: "gizem" },
      { id: 6, name: "Fantastik", slug: "fantastik" },
    ],
  },
];

export const demoTrendDiziler: ContentCard[] = [
  ...demoHeroItems.filter((i) => i.type === "SERIES"),
  {
    id: "6",
    title: "Severance",
    originalTitle: "Severance",
    slug: "severance",
    type: "SERIES",
    description:
      "Mark, çalışanların iş ve kişisel anılarının cerrahi olarak birbirinden ayrıldığı gizemli bir şirkette çalışır. Bir grup meslektaşıyla birlikte işverenlerinin gerçek doğasını keşfetmeye başlarlar.",
    posterUrl: "https://image.tmdb.org/t/p/w500/lFGHFVtaf6HM4tFiMiQLbClBkcj.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/75GciJFPM08p3FfPtri5z6rYdX5.jpg",
    tmdbId: 95396,
    imdbRating: 8.7,
    releaseYear: 2022,
    durationMinutes: 50,
    country: "ABD",
    language: "İngilizce",
    quality: "4K",
    viewCount: 65000,
    status: "ACTIVE",
    genres: [
      { id: 1, name: "Drama", slug: "drama" },
      { id: 5, name: "Gerilim", slug: "gerilim" },
      { id: 7, name: "Bilim Kurgu", slug: "bilim-kurgu" },
    ],
  },
  {
    id: "7",
    title: "The Bear",
    originalTitle: "The Bear",
    slug: "the-bear",
    type: "SERIES",
    description:
      "Genç bir şef, ailesinin küçük sandviç dükkanını devraldıktan sonra kaotik mutfak dünyasıyla yüzleşir.",
    posterUrl: "https://image.tmdb.org/t/p/w500/sHFlZKMFAYMKp0jHo9TjQer8YkG.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/aAdRjSFINxdWP2cYxiuGNLGHNJA.jpg",
    tmdbId: 136315,
    imdbRating: 8.6,
    releaseYear: 2022,
    durationMinutes: 30,
    country: "ABD",
    language: "İngilizce",
    quality: "HD",
    viewCount: 54000,
    status: "ACTIVE",
    genres: [
      { id: 1, name: "Drama", slug: "drama" },
      { id: 8, name: "Komedi", slug: "komedi" },
    ],
  },
];

export const demoPopulerFilmler: ContentCard[] = [
  ...demoHeroItems.filter((i) => i.type === "MOVIE"),
  {
    id: "8",
    title: "Killers of the Flower Moon",
    originalTitle: "Killers of the Flower Moon",
    slug: "killers-of-the-flower-moon",
    type: "MOVIE",
    description:
      "1920'lerde Oklahoma'da Osage Ulusu'nun üyelerine yönelik seri cinayetlerin ardındaki karanlık komplo.",
    posterUrl: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    tmdbId: 466420,
    imdbRating: 7.7,
    releaseYear: 2023,
    durationMinutes: 206,
    country: "ABD",
    language: "İngilizce",
    quality: "4K",
    viewCount: 43000,
    status: "ACTIVE",
    genres: [
      { id: 1, name: "Drama", slug: "drama" },
      { id: 10, name: "Suç", slug: "suc" },
      { id: 4, name: "Tarih", slug: "tarih" },
    ],
  },
  {
    id: "9",
    title: "Poor Things",
    originalTitle: "Poor Things",
    slug: "poor-things",
    type: "MOVIE",
    description:
      "Genç bir kadının olağanüstü yolculuğu. Bilim insanı Dr. Godwin Baxter tarafından hayata döndürülen Bella, dünyayı keşfetmeye çıkar.",
    posterUrl: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc9fgem.jpg",
    tmdbId: 792307,
    imdbRating: 8.0,
    releaseYear: 2023,
    durationMinutes: 141,
    country: "İrlanda",
    language: "İngilizce",
    quality: "HD",
    viewCount: 38000,
    status: "ACTIVE",
    genres: [
      { id: 8, name: "Komedi", slug: "komedi" },
      { id: 1, name: "Drama", slug: "drama" },
      { id: 11, name: "Romantik", slug: "romantik" },
    ],
  },
  {
    id: "10",
    title: "Godzilla x Kong: The New Empire",
    originalTitle: "Godzilla x Kong: The New Empire",
    slug: "godzilla-x-kong",
    type: "MOVIE",
    description:
      "İki efsanevi titan, insanlığın varlığını tehdit eden devasa bir keşfe karşı birlikte mücadele eder.",
    posterUrl: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDV4jC1kJzEVVV5.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg",
    tmdbId: 823464,
    imdbRating: 6.5,
    releaseYear: 2024,
    durationMinutes: 115,
    country: "ABD",
    language: "İngilizce",
    quality: "HD",
    viewCount: 67000,
    status: "ACTIVE",
    genres: [
      { id: 2, name: "Aksiyon", slug: "aksiyon" },
      { id: 7, name: "Bilim Kurgu", slug: "bilim-kurgu" },
      { id: 3, name: "Macera", slug: "macera" },
    ],
  },
];

export const demoYeniEklenenler: ContentCard[] = [
  demoHeroItems[4], // Wednesday
  demoTrendDiziler[3], // Severance
  demoPopulerFilmler[2], // Poor Things
  demoHeroItems[3], // Dune Part Two
  demoTrendDiziler[4], // The Bear
  demoPopulerFilmler[3], // Godzilla x Kong
].filter(Boolean) as ContentCard[];
